surface.CreateFont("NarutoFont", {
	font = "Ninja Naruto",
	extended = true,
	size = ScreenScale(7),
	weight = 500,
	blursize = 0,
	scanlines = 0,
	antialias = true,
	underline = false,
	italic = false,
	strikeout = false,
	symbol = false,
	rotary = false,
	shadow = false,
	additive = false,
	outline = false,
})